server:
  port: 8081


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
spring:
  application:
    name: DemoServer
info:
  msg: ok
